name: 'Gitsign Verify'

description: 'Uses `gitsign` to verify commit signatures of a branch'

inputs:
  version:
    description: 'Version of `gitsign` binary'
    required: true
    default: '0.3.1'

  ref:
    description: 'Git ref to check against'
    required: true
    default: 'origin/master'

# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Install Gitsign
      shell: bash
      run: |
        # Get binary
        wget -q https://github.com/sigstore/gitsign/releases/download/v${{ inputs.version }}/gitsign_${{ inputs.version }}_linux_amd64 -O gitsign

        # Set gitsign as git commit verifier
        git config --local gpg.x509.program $(pwd)/gitsign
        git config --local gpg.format x509

    - name: Verify Commits
      shell: bash
      run: |
        COMMITS="$(git rev-list ${{ inputs.main-branch }}..HEAD)"
        echo "[*] Verifying commits: '$COMMITS'"

        for commit in ${COMMITS}; do
          # If script fails, the action stops
          ./verify-commit.sh "$commit"
        done
